spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 开启默认的路由规则  会根据注册中心的服务名作为路径实现路由规则
          enabled: false
      routes:
        - id: path
          uri: lb://order
          # 当请求满足 predicate 断言后将请求路由到 uri
          predicates:
            - Path=/order/**
#            - After=2026-05-14T17:42:47.789+08:00[Asia/Shanghai]
#            - Header=X-Request-Id, \d+
          filters:
            - AddRequestHeader=X-Request-Id, 1926
            - AddRequestParameter=red, blue
            - AddResponseHeader=X-Response-Red, Blue
            - StripPrefix=1

server:
  port: 80

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
