spring:
  profiles:
    active: test

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # district_id  ==   districtId
    map-underscore-to-camel-case: true
logging:
  level:
    org.example.mapper: debug
    org.mybatis: debug
