spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/air_quality_detection_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # district_id  ==   districtId
    map-underscore-to-camel-case: true
logging:
  level:
    org.example.mapper: debug
    org.mybatis: debug