# ???????? DEBUG????????????????????
log4j.rootLogger=DEBUG, console

# ???????? Appender
log4j.appender.console=org.apache.log4j.ConsoleAppender
# ?????? System.out???? System.err??????
log4j.appender.console.Target=System.out
# ?????????????????????????
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} [%p] %c - %m%n