package org.example.pojo;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.DEPTNO
     *
     * @mbggenerated Sun Mar 22 21:31:29 CST 2026
     */
    private Integer deptno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.DNAME
     *
     * @mbggenerated Sun Mar 22 21:31:29 CST 2026
     */
    private String dname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.LOC
     *
     * @mbggenerated Sun Mar 22 21:31:29 CST 2026
     */
    private String loc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.DEPTNO
     *
     * @return the value of dept.DEPTNO
     *
     * @mbggenerated Sun Mar 22 21:31:29 CST 2026
     */
    public Integer getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.DEPTNO
     *
     * @param deptno the value for dept.DEPTNO
     *
     * @mbggenerated Sun Mar 22 21:31:29 CST 2026
     */
    public void setDeptno(Integer deptno) {
        this.deptno = deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.DNAME
     *
     * @return the value of dept.DNAME
     *
     * @mbggenerated Sun Mar 22 21:31:29 CST 2026
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.DNAME
     *
     * @param dname the value for dept.DNAME
     *
     * @mbggenerated Sun Mar 22 21:31:29 CST 2026
     */
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.LOC
     *
     * @return the value of dept.LOC
     *
     * @mbggenerated Sun Mar 22 21:31:29 CST 2026
     */
    public String getLoc() {
        return loc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.LOC
     *
     * @param loc the value for dept.LOC
     *
     * @mbggenerated Sun Mar 22 21:31:29 CST 2026
     */
    public void setLoc(String loc) {
        this.loc = loc == null ? null : loc.trim();
    }
}