package org.example.pojo;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.pid
     *
     * @mbggenerated Sun Mar 22 21:32:28 CST 2026
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.pname
     *
     * @mbggenerated Sun Mar 22 21:32:28 CST 2026
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.money
     *
     * @mbggenerated Sun Mar 22 21:32:28 CST 2026
     */
    private Integer money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.pid
     *
     * @return the value of projects.pid
     *
     * @mbggenerated Sun Mar 22 21:32:28 CST 2026
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.pid
     *
     * @param pid the value for projects.pid
     *
     * @mbggenerated Sun Mar 22 21:32:28 CST 2026
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.pname
     *
     * @return the value of projects.pname
     *
     * @mbggenerated Sun Mar 22 21:32:28 CST 2026
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.pname
     *
     * @param pname the value for projects.pname
     *
     * @mbggenerated Sun Mar 22 21:32:28 CST 2026
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.money
     *
     * @return the value of projects.money
     *
     * @mbggenerated Sun Mar 22 21:32:28 CST 2026
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.money
     *
     * @param money the value for projects.money
     *
     * @mbggenerated Sun Mar 22 21:32:28 CST 2026
     */
    public void setMoney(Integer money) {
        this.money = money;
    }
}