# MySQL 8.0+ Driver
jdbc.driver=com.mysql.cj.jdbc.Driver
# Database Connection URL
jdbc.url=jdbc:mysql://127.0.0.1:3306/MybatisDB?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
# Database Username
jdbc.username=root
# Database Password
jdbc.password=root