package org.example.mapper;

import org.example.pojo.Project;

public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbggenerated Sun Mar 22 21:32:28 CST 2026
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbggenerated Sun Mar 22 21:32:28 CST 2026
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbggenerated Sun Mar 22 21:32:28 CST 2026
     */
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbggenerated Sun Mar 22 21:32:28 CST 2026
     */
    Project selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbggenerated Sun Mar 22 21:32:28 CST 2026
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbggenerated Sun Mar 22 21:32:28 CST 2026
     */
    int updateByPrimaryKey(Project record);
}