metadata:
- appName: ''
  dataId: beacon-api-dev.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: beacon-cache-dev.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: beacon-strategy-dev.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: beacon-search-dev.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: beacon-push-dev.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: beacon-smsgateway-dev.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: beacon-monitor-dev.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
